### ISSUE TITLE
`logSQL()` messing up console if there is binary BLOB param

### ISSUE THREAD

**Issue by afriza** [ganigeorgiev/ozzo-dbx#2]
The [`logSQL()`](https://github.com/pocketbase/dbx/blob/cecf5a8e6bf29b310700db58ef0e35a394bbe87d/query.go#L100) function caused problem in the console when I inserted binary `BLOB` and [`ExecLogFunc`](https://github.com/pocketbase/dbx#logging-executed-sql-statements) is set to print the SQL.

https://github.com/pocketbase/dbx/blob/cecf5a8e6bf29b310700db58ef0e35a394bbe87d/query.go#L109-L110

For now, in `ExecLogFunc` I check using string matching if the SQL is involving binary BLOB and don't print it to console.

**Comment by ganigeorgiev** [comment]
I've updated the default logger in v1.9 to print the raw bytes as hex since that is how most db tools (including sqlite3 with `mode .quote`) seems to handle it.

**Comment by afriza** [comment]
Thank you.

Even better, maybe in future, if there's a max limit..

I saw some go logs showing initial & last few number of bytes as hex.. and the middle shows something like `[... 5678 bytes of data ... ]`
