### ISSUE TITLE
newQuery does not honor cascade delete

### ISSUE THREAD

**Issue by ericbaek** [ganigeorgiev/ozzo-dbx#5]
### Context
We have three collections in our database: **Comments, Posts, and Tickets**. Each record in the comment collection has a relation to a record in the posts collection. Cascade delete is enabled to ensure that all comments related to a post are deleted when the post is deleted.
```
    +-----------+           +---------+
    |   Posts   |           | Tickets |
    +-----------+           +---------+
         ^
         |
         |
    +-----------+
    |  Comments |
    +-----------+
```

### Problem
When a new ticket is registered, I need to delete a specific post along with its related comments. However, the current approach only deletes the post, leaving the related comments intact.

Similar issue was registered about a year ago.
[dbx.Query Delete does not honor cascade delete](https://github.com/pocketbase/dbx/issues/3)

Here is the code snippet that attempts to delete a post and its related comments upon ticket creation:
```js
onModelBeforeCreate((e) => {
    $app.dao().db().newQuery(`DELETE FROM Posts WHERE id = 'test00000000000'`).execute()
}, "Tickets")
``` 
This code successfully deletes the post with ID test00000000000, but it does not delete the comments related to this post.

The same issue occurs when using a transaction:
```js
$app.dao().runInTransaction((txDao) => {
   txDao.db().newQuery(`DELETE FROM Posts WHERE id = 'test00000000000').execute()
}
```

https://github.com/pocketbase/dbx/assets/43541203/4f795304-d921-41c8-9e6e-abe7cda4cb36

**Comment by ganigeorgiev** [comment]
It is not documented at the moment but it is working correctly.

Raw SQL queries doesn't trigger the cascade operations.
They are triggered on application level when using the designated `deleteRecord` Dao method.

**Comment by ganigeorgiev** [comment]
I've also just noticed that this was posted in the `dbx` repo.

Note that the above behavior is only PocketBase specific because the cascade handling is "dynamic" and also needs to handle the multiple `relation` field values update/delete behavior.
